const { useMemo, useState, useEffect } = React;
const { generateRoundRobinSchedule } = window.scheduleLogic;

const initialEvents = [
  {
    id: 1,
    title: 'Opening Match',
    date: '2026-08-05',
    type: 'match',
    venue: 'Main Ground',
    fee: 1200,
    reminder: 'Team briefing at 6 PM'
  },
  {
    id: 2,
    title: 'Semi Final',
    date: '2026-08-10',
    type: 'fee',
    venue: 'Finance Desk',
    fee: 500,
    reminder: 'Fee due for all registered teams'
  }
];

const monthNames = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
const weekdays = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];

function formatDateKey(date) {
  const year = date.getFullYear();
  const month = `${date.getMonth() + 1}`.padStart(2, '0');
  const day = `${date.getDate()}`.padStart(2, '0');
  return `${year}-${month}-${day}`;
}

function addDays(date, days) {
  const result = new Date(date);
  result.setDate(result.getDate() + days);
  return result;
}

function formatMonthKey(date) {
  return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-01`;
}

function safeReadStorage(key, fallback) {
  try {
    const value = localStorage.getItem(key);
    return value ? JSON.parse(value) : fallback;
  } catch (error) {
    return fallback;
  }
}

function safeWriteStorage(key, value) {
  try {
    localStorage.setItem(key, JSON.stringify(value));
  } catch (error) {
    // ignore storage errors
  }
}

function App() {
  const [tournaments, setTournaments] = useState(() => safeReadStorage('tournaments', [{
    id: 'default',
    name: 'Main Tournament',
    events: initialEvents,
    tournamentType: 'weekday',
    slotPreferences: ['6am', '10am', '2pm', '5pm', '8pm'],
    teamNames: ['Team 1', 'Team 2', 'Team 3', 'Team 4', 'Team 5', 'Team 6', 'Team 7', 'Team 8'],
    playDay: 'saturday',
    currentMonth: '2026-08-01',
    hasAutoGenerated: false
  }]));
  const [activeTournamentId, setActiveTournamentId] = useState(() => safeReadStorage('active-tournament-id', 'default'));
  const [showModal, setShowModal] = useState(false);
  const [form, setForm] = useState({
    title: '',
    date: '',
    type: 'match',
    venue: '',
    fee: '',
    reminder: '',
    mobile: ''
  });
  const [warning, setWarning] = useState('');
  const [editingMatchId, setEditingMatchId] = useState(null);
  const [editForm, setEditForm] = useState({ date: '', slot: '', title: '', fee: '', team: '' });
  const [newTournamentName, setNewTournamentName] = useState('');
  const [newTournamentFee, setNewTournamentFee] = useState('0');
  const [showCreateTournament, setShowCreateTournament] = useState(false);
  const [viewMode, setViewMode] = useState('dashboard');
  const [activeReminderId, setActiveReminderId] = useState(null);
  const [customReminderText, setCustomReminderText] = useState('');
  const [paymentReminderId, setPaymentReminderId] = useState(null);
  const [paymentReminderText, setPaymentReminderText] = useState('');

  const activeTournament = tournaments.find((item) => item.id === activeTournamentId) || tournaments[0];
  const events = activeTournament?.events || [];
  const tournamentType = activeTournament?.tournamentType || 'weekday';
  const slotPreferences = activeTournament?.slotPreferences || ['6am', '10am', '2pm', '5pm', '8pm'];
  const teamNames = activeTournament?.teamNames || ['Team 1', 'Team 2', 'Team 3', 'Team 4', 'Team 5', 'Team 6', 'Team 7', 'Team 8'];
  const playDay = activeTournament?.playDay || 'saturday';
  const currentMonth = new Date(activeTournament?.currentMonth || '2026-08-01');
  const paymentReminders = useMemo(() => {
    if (Array.isArray(activeTournament?.paymentReminders) && activeTournament.paymentReminders.length) {
      return activeTournament.paymentReminders;
    }

    return (teamNames || []).map((team, index) => ({
      id: `pay-${index + 1}`,
      team,
      amount: activeTournament?.matchFee || 0,
      dueDate: '',
      mobile: '',
      note: ''
    }));
  }, [activeTournament, teamNames]);
  const hasAutoGenerated = activeTournament?.hasAutoGenerated || false;
  const monthStart = new Date(currentMonth.getFullYear(), currentMonth.getMonth(), 1);
  const monthEnd = new Date(currentMonth.getFullYear(), currentMonth.getMonth() + 1, 0);
  const leadingEmptyDays = monthStart.getDay();
  const totalDays = monthEnd.getDate();
  const cells = [];

  for (let i = 0; i < leadingEmptyDays; i += 1) cells.push(null);
  for (let day = 1; day <= totalDays; day += 1) cells.push(new Date(currentMonth.getFullYear(), currentMonth.getMonth(), day));

  const dayEventsMap = useMemo(() => {
    const map = {};
    events.forEach((event) => {
      const key = event.date;
      if (!map[key]) map[key] = [];
      map[key].push(event);
    });
    return map;
  }, [events]);

  const conflicts = useMemo(() => {
    const byDate = {};
    events.forEach((event) => {
      if (!byDate[event.date]) byDate[event.date] = [];
      byDate[event.date].push(event);
    });
    return Object.entries(byDate).filter(([, list]) => list.length > 1).map(([date]) => date);
  }, [events]);

  const autoSchedule = useMemo(() => {
    return generateRoundRobinSchedule(teamNames, slotPreferences);
  }, [teamNames, slotPreferences]);

  const reminderList = useMemo(() => {
    return [...events].sort((a, b) => a.date.localeCompare(b.date));
  }, [events]);

  const upcoming = useMemo(() => {
    return reminderList.slice(0, 5);
  }, [reminderList]);

  const buildGeneratedEvents = (baseDate = '2026-08-01', fee = activeTournament?.matchFee || 0) => {
    return generateRoundRobinSchedule(teamNames, slotPreferences, {
      tournamentType,
      playDay,
      startDate: baseDate
    }).map((match, index) => ({
      id: 1000 + index,
      title: `${match.home} vs ${match.away}`,
      date: match.date,
      type: 'match',
      venue: match.venue,
      fee,
      generated: true,
      reminder: `Slot ${match.slot} • ${tournamentType === 'weekend' ? 'Weekend' : 'Weekday'} tournament`
    }));
  };

  useEffect(() => {
    if (!activeTournament) return;
    if (hasAutoGenerated) return;

    const generatedEvents = buildGeneratedEvents('2026-08-01', activeTournament?.matchFee || 0);
    const existingEvents = events.filter((item) => !item.generated);
    updateTournament(activeTournament.id, { events: [...existingEvents, ...generatedEvents], hasAutoGenerated: true, currentMonth: `${generatedEvents[0]?.date?.slice(0, 7) || '2026-08'}-01` });
    const firstGeneratedDate = generatedEvents[0]?.date;
    if (firstGeneratedDate) {
      const [year, month] = firstGeneratedDate.split('-').map(Number);
      updateTournament(activeTournament.id, { currentMonth: formatMonthKey(new Date(year, month - 1, 1)) });
    }
  }, [activeTournament, hasAutoGenerated, tournamentType, teamNames, slotPreferences, activeTournament?.matchFee]);

  useEffect(() => {
    safeWriteStorage('tournaments', tournaments);
    safeWriteStorage('active-tournament-id', activeTournamentId);
  }, [tournaments, activeTournamentId]);

  const updateTournament = (id, updates) => {
    setTournaments((prev) => prev.map((item) => item.id === id ? { ...item, ...updates } : item));
  };

  const updatePaymentEntry = (id, updates) => {
    if (!activeTournament) return;
    updateTournament(activeTournament.id, {
      paymentReminders: paymentReminders.map((item) => item.id === id ? { ...item, ...updates } : item)
    });
  };

  const handleChange = (e) => {
    const { name, value } = e.target;
    setForm((prev) => ({ ...prev, [name]: value }));
  };

  const validateConflict = (date) => {
    const sameDate = events.filter((event) => event.date === date);
    return sameDate.length > 0 ? `Warning: ${sameDate.length} item(s) already scheduled on ${date}.` : '';
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    if (!form.title || !form.date || !form.venue || !form.reminder) {
      setWarning('Please fill in all required fields.');
      return;
    }

    const conflictMessage = validateConflict(form.date);
    if (conflictMessage) {
      setWarning(conflictMessage);
      return;
    }

    const newEvent = {
      id: Date.now(),
      title: form.title,
      date: form.date,
      type: form.type,
      venue: form.venue,
      fee: Number(form.fee || 0),
      reminder: form.reminder,
      mobile: form.mobile
    };

    updateTournament(activeTournament.id, { events: [...events, newEvent] });
    setForm({ title: '', date: '', type: 'match', venue: '', fee: '', reminder: '', mobile: '' });
    setWarning('');
    setShowModal(false);
  };

  const handleGenerateSchedule = () => {
    const baseDate = form.date || '2026-08-01';
    const generatedEvents = buildGeneratedEvents(baseDate, activeTournament?.matchFee || 0);
    const existingEvents = events.filter((item) => !item.generated);

    updateTournament(activeTournament.id, { events: [...existingEvents, ...generatedEvents], hasAutoGenerated: true, currentMonth: `${generatedEvents[0]?.date?.slice(0, 7) || '2026-08'}-01` });
    setShowModal(false);
    setWarning('');
    const firstGeneratedDate = generatedEvents[0]?.date;
    if (firstGeneratedDate) {
      const [year, month] = firstGeneratedDate.split('-').map(Number);
      updateTournament(activeTournament.id, { currentMonth: formatMonthKey(new Date(year, month - 1, 1)) });
    }
  };

  const startEdit = (item) => {
    setEditingMatchId(item.id);
    const slot = item.reminder?.replace(/^Slot\s*/, '').split(' • ')[0] || '';
    setEditForm({
      date: item.date,
      slot,
      title: item.title || '',
      fee: item.fee != null ? String(item.fee) : '',
      team: item.team || item.title || ''
    });
  };

  const saveEdit = () => {
    updateTournament(activeTournament.id, {
      events: events.map((item) => item.id === editingMatchId ? {
        ...item,
        title: editForm.title || item.title,
        team: editForm.team || item.team || item.title,
        fee: Number(editForm.fee || 0),
        date: editForm.date,
        reminder: item.type === 'match' ? `Slot ${editForm.slot} • ${item.reminder.split(' • ')[1] || 'Tournament'}` : item.reminder
      } : item)
    });
    setEditingMatchId(null);
    setEditForm({ date: '', slot: '', title: '', fee: '', team: '' });
  };

  const deleteMatch = (id) => {
    updateTournament(activeTournament.id, { events: events.filter((item) => item.id !== id) });
  };

  const openReminderComposer = (item) => {
    setActiveReminderId(item.id);
    setCustomReminderText(`Hello!\n\nThis is a reminder for ${item.title}.\nDate: ${item.date}\nVenue: ${item.venue}\nFee: ₹${item.fee || 0}\n\nPlease make the payment at the earliest. Thank you.`);
  };

  const sendWhatsAppReminder = (item) => {
    if (!item.mobile) {
      window.alert('Add a mobile number to this reminder first.');
      return;
    }

    const phone = item.mobile.replace(/[^\d]/g, '');
    const message = encodeURIComponent(customReminderText.trim() || `Hello!\n\nThis is a reminder for ${item.title}.`);
    window.open(`https://wa.me/${phone}?text=${message}`, '_blank', 'noopener,noreferrer');
    setActiveReminderId(null);
    setCustomReminderText('');
  };

  const openPaymentReminder = (item) => {
    setPaymentReminderId(item.id);
    setPaymentReminderText(`Hello ${item.team}!\n\nThis is a payment reminder for the tournament dues.\nAmount due: ₹${item.amount || 0}\nDue date: ${item.dueDate || 'To be confirmed'}\n\nPlease complete the payment at the earliest. Thank you.`);
  };

  const sendPaymentReminder = (item) => {
    if (!item.mobile) {
      window.alert('Add a mobile number for this team first.');
      return;
    }

    const phone = item.mobile.replace(/[^\d]/g, '');
    const message = encodeURIComponent(paymentReminderText.trim() || `Hello ${item.team}!\n\nThis is a payment reminder for your tournament dues.`);
    window.open(`https://wa.me/${phone}?text=${message}`, '_blank', 'noopener,noreferrer');
    setPaymentReminderId(null);
    setPaymentReminderText('');
  };

  const changeMonth = (offset) => {
    const nextMonth = new Date(currentMonth.getFullYear(), currentMonth.getMonth() + offset, 1);
    updateTournament(activeTournament.id, { currentMonth: formatMonthKey(nextMonth) });
  };

  const createTournament = () => {
    if (!newTournamentName.trim()) return;
    const matchFeeValue = Number(newTournamentFee || 0);
    const id = `t-${Date.now()}`;
    const seededEvents = buildGeneratedEvents('2026-08-01', matchFeeValue).map((event, index) => ({ ...event, id: 100000 + index }));
    const initialMonth = seededEvents[0]?.date ? formatMonthKey(new Date(`${seededEvents[0].date.slice(0, 7)}-01`)) : '2026-08-01';
    const newTournament = {
      id,
      name: newTournamentName.trim(),
      events: seededEvents,
      tournamentType: 'weekday',
      slotPreferences: ['6am', '10am', '2pm', '5pm', '8pm'],
      teamNames: ['Team 1', 'Team 2', 'Team 3', 'Team 4', 'Team 5', 'Team 6', 'Team 7', 'Team 8'],
      playDay,
      matchFee: matchFeeValue,
      paymentReminders: ['Team 1', 'Team 2', 'Team 3', 'Team 4', 'Team 5', 'Team 6', 'Team 7', 'Team 8'].map((team, index) => ({
        id: `pay-${id}-${index + 1}`,
        team,
        amount: matchFeeValue,
        dueDate: '',
        mobile: '',
        note: ''
      })),
      currentMonth: initialMonth,
      hasAutoGenerated: true
    };
    setTournaments((prev) => [...prev, newTournament]);
    setActiveTournamentId(id);
    setNewTournamentName('');
    setNewTournamentFee('0');
    setShowCreateTournament(false);
  };

  return (
    <div className="app-shell">
      <div className="hero">
        <div>
          <h1>Cricket Tournament Admin Desk</h1>
          <p>Create match plans, reminder alerts, and fee updates from one place.</p>
        </div>
        <div className="hero-actions">
          <div className="view-toggle">
            <button className={`btn ${viewMode === 'dashboard' ? 'btn-primary' : ''}`} onClick={() => setViewMode('dashboard')}>Dashboard</button>
            <button className={`btn ${viewMode === 'reminders' ? 'btn-primary' : ''}`} onClick={() => setViewMode('reminders')}>Reminder cards</button>
            <button className={`btn ${viewMode === 'payments' ? 'btn-primary' : ''}`} onClick={() => setViewMode('payments')}>Payments</button>
          </div>
          <button className="btn btn-primary" onClick={() => setShowModal(true)}>+ Add Schedule</button>
        </div>
      </div>

      <div className="panel" style={{ marginBottom: 16 }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 8, flexWrap: 'wrap' }}>
          <h3 style={{ margin: 0 }}>Tournaments</h3>
          <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
            {tournaments.map((item) => (
              <button key={item.id} className={`btn ${activeTournamentId === item.id ? 'btn-primary' : ''}`} onClick={() => setActiveTournamentId(item.id)}>{item.name}</button>
            ))}
            <button className="btn" onClick={() => setShowCreateTournament(true)}>+ New Tournament</button>
          </div>
        </div>
        {showCreateTournament && (
          <div style={{ marginTop: 12 }} className="field-group">
            <input value={newTournamentName} onChange={(e) => setNewTournamentName(e.target.value)} placeholder="Tournament name" />
            <input type="number" value={newTournamentFee} onChange={(e) => setNewTournamentFee(e.target.value)} placeholder="Match fee (₹)" style={{ marginTop: 8 }} />
            <div className="actions">
              <button className="btn" onClick={() => setShowCreateTournament(false)}>Cancel</button>
              <button className="btn btn-primary" onClick={createTournament}>Create</button>
            </div>
          </div>
        )}
      </div>

      <div className="panel" style={{ marginBottom: 16 }}>
        <h3 style={{ marginTop: 0 }}>Tournament preferences</h3>
        <div className="field-row">
          <div className="field-group">
            <label>Tournament mode</label>
            <select value={tournamentType} onChange={(e) => updateTournament(activeTournament.id, { tournamentType: e.target.value })}>
              <option value="weekday">Weekday</option>
              <option value="weekend">Weekend</option>
            </select>
          </div>
          <div className="field-group">
            <label>Slots</label>
            <input value={slotPreferences.join(', ')} onChange={(e) => updateTournament(activeTournament.id, { slotPreferences: e.target.value.split(',').map((slot) => slot.trim()).filter(Boolean) })} placeholder="6am, 10am, 2pm, 5pm, 8pm" />
          </div>
        </div>
        <div className="field-group">
          <label>Teams</label>
          <input value={teamNames.join(', ')} onChange={(e) => updateTournament(activeTournament.id, { teamNames: e.target.value.split(',').map((team) => team.trim()).filter(Boolean) })} placeholder="Team 1, Team 2, ..." />
        </div>
        <div className="field-group">
          <label>Play on</label>
          <select value={playDay} onChange={(e) => updateTournament(activeTournament.id, { playDay: e.target.value })}>
            <option value="saturday">Saturday</option>
            <option value="sunday">Sunday</option>
          </select>
        </div>
        <div className="field-group">
          <label>Match fee (₹)</label>
          <input type="number" value={activeTournament?.matchFee ?? 0} onChange={(e) => updateTournament(activeTournament.id, { matchFee: Number(e.target.value || 0) })} placeholder="1200" />
        </div>
        <div className="actions">
          <button className="btn btn-primary" onClick={handleGenerateSchedule}>Generate all-play-all schedule</button>
        </div>
      </div>

      <div className="stats">
        <div className="stat-card">
          <span className="muted">Total Entries</span>
          <strong>{events.length}</strong>
        </div>
        <div className="stat-card">
          <span className="muted">Conflicts</span>
          <strong>{conflicts.length}</strong>
        </div>
        <div className="stat-card">
          <span className="muted">Next Reminder</span>
          <strong>{upcoming[0] ? upcoming[0].date : '—'}</strong>
        </div>
      </div>

      {viewMode === 'payments' ? (
        <section className="panel">
          <div className="section-header">
            <h3 style={{ margin: 0 }}>Team payment reminders</h3>
            <button className="btn" onClick={() => setViewMode('dashboard')}>Back to dashboard</button>
          </div>
          <div className="list reminder-list">
            {paymentReminders.map((item) => (
              <div key={item.id} className="reminder-card">
                <strong>{item.team}</strong>
                <div className="muted">Amount due: ₹{item.amount || 0}</div>
                <div className="muted">Due date: {item.dueDate || 'Set a due date'}</div>
                <div className="field-group">
                  <label>Amount due (₹)</label>
                  <input type="number" value={item.amount || 0} onChange={(e) => updatePaymentEntry(item.id, { amount: Number(e.target.value || 0) })} placeholder="Amount" />
                </div>
                <div className="field-group">
                  <label>Due date</label>
                  <input type="date" value={item.dueDate || ''} onChange={(e) => updatePaymentEntry(item.id, { dueDate: e.target.value })} />
                </div>
                <div className="field-group">
                  <label>Mobile number</label>
                  <input value={item.mobile || ''} onChange={(e) => updatePaymentEntry(item.id, { mobile: e.target.value })} placeholder="91XXXXXXXXXX" />
                </div>
                <div className="field-group">
                  <label>Note</label>
                  <input value={item.note || ''} onChange={(e) => updatePaymentEntry(item.id, { note: e.target.value })} placeholder="Follow-up note" />
                </div>
                {paymentReminderId === item.id ? (
                  <div className="field-group">
                    <label>Reminder message</label>
                    <textarea value={paymentReminderText} onChange={(e) => setPaymentReminderText(e.target.value)} rows="4" style={{ width: '100%', padding: '10px 12px', borderRadius: '10px', border: '1px solid rgba(255,255,255,0.15)', background: 'var(--panel-2)', color: 'var(--text)' }} />
                    <div className="actions">
                      <button className="btn" onClick={() => setPaymentReminderId(null)}>Cancel</button>
                      <button className="btn btn-primary" onClick={() => sendPaymentReminder(item)}>Send reminder</button>
                    </div>
                  </div>
                ) : (
                  <div className="actions">
                    <button className="btn btn-primary" onClick={() => openPaymentReminder(item)}>Reminder</button>
                  </div>
                )}
              </div>
            ))}
          </div>
        </section>
      ) : viewMode === 'reminders' ? (
        <section className="panel">
          <div className="section-header">
            <h3 style={{ margin: 0 }}>All reminder cards</h3>
            <button className="btn" onClick={() => setViewMode('dashboard')}>Back to dashboard</button>
          </div>
          <div className="list reminder-list">
            {reminderList.map((item) => (
              <div key={item.id} className={`reminder-card ${item.type === 'fee' ? 'fee' : ''}`}>
                <strong>{item.title}</strong>
                <div className="muted">{item.date} • {item.venue}</div>
                <div>{item.reminder}</div>
                <div className="muted">Fee: {item.fee || 0}</div>
                {item.mobile ? <div className="muted">WhatsApp: {item.mobile}</div> : null}
                <div style={{ marginTop: 8 }}>
                  {activeReminderId === item.id ? (
                    <div className="field-group">
                      <label>Custom reminder message</label>
                      <textarea value={customReminderText} onChange={(e) => setCustomReminderText(e.target.value)} rows="4" style={{ width: '100%', padding: '10px 12px', borderRadius: '10px', border: '1px solid rgba(255,255,255,0.15)', background: 'var(--panel-2)', color: 'var(--text)' }} />
                      <div className="actions">
                        <button className="btn" onClick={() => setActiveReminderId(null)}>Cancel</button>
                        <button className="btn btn-primary" onClick={() => sendWhatsAppReminder(item)}>Send reminder</button>
                      </div>
                    </div>
                  ) : (
                    <button className="btn btn-primary" onClick={() => openReminderComposer(item)}>Reminder</button>
                  )}
                </div>
                {item.type === 'match' && (
                  <div style={{ marginTop: 8 }}>
                    {editingMatchId === item.id ? (
                      <div className="field-group">
                        <label>Team / Title</label>
                        <select value={editForm.team} onChange={(e) => setEditForm((prev) => ({ ...prev, team: e.target.value, title: e.target.value }))}>
                          {teamNames.map((team) => <option key={team} value={team}>{team}</option>)}
                        </select>
                        <label>Date</label>
                        <input type="date" value={editForm.date} onChange={(e) => setEditForm((prev) => ({ ...prev, date: e.target.value }))} />
                        {item.type === 'match' ? <>
                          <label>Slot</label>
                          <input value={editForm.slot} onChange={(e) => setEditForm((prev) => ({ ...prev, slot: e.target.value }))} placeholder="Slot" />
                        </> : null}
                        <label>Fee (₹)</label>
                        <input type="number" value={editForm.fee} onChange={(e) => setEditForm((prev) => ({ ...prev, fee: e.target.value }))} placeholder="Fee" />
                        <div className="actions">
                          <button className="btn" onClick={() => setEditingMatchId(null)}>Cancel</button>
                          <button className="btn btn-primary" onClick={saveEdit}>Save</button>
                        </div>
                      </div>
                    ) : (
                      <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
                        <button className="btn" onClick={() => startEdit(item)}>Edit day & time</button>
                        <button className="btn" style={{ background: '#ff5f7e', color: 'white' }} onClick={() => deleteMatch(item.id)}>Delete</button>
                      </div>
                    )}
                  </div>
                )}
              </div>
            ))}
          </div>
        </section>
      ) : (
        <div className="grid">
          <section className="panel">
            <div className="month-nav">
              <button className="btn" onClick={() => changeMonth(-1)}>← Prev</button>
              <h3 style={{ margin: 0 }}>{monthNames[currentMonth.getMonth()]} {currentMonth.getFullYear()}</h3>
              <button className="btn" onClick={() => changeMonth(1)}>Next →</button>
            </div>
            <div className="calendar-grid">
              {weekdays.map((day) => <div key={day} className="calendar-head">{day}</div>)}
              {cells.map((date, index) => {
                if (!date) return <div key={`empty-${index}`} className="day-cell muted" />;
                const key = formatDateKey(date);
                const items = dayEventsMap[key] || [];
                const hasConflict = conflicts.includes(key);
                const isSaturday = date.getDay() === 6;
                const isSunday = date.getDay() === 0;
                const dayClass = isSaturday ? 'saturday' : isSunday ? 'sunday' : '';
                return (
                  <div key={key} className={`day-cell ${dayClass} ${hasConflict ? 'conflict' : ''}`}>
                    <div className="day-label">{date.getDate()}</div>
                    {items.map((item) => (
                      <div key={item.id} className={`chip ${item.type === 'fee' ? 'warning' : ''}`}>
                        {item.title}
                      </div>
                    ))}
                  </div>
                );
              })}
            </div>
          </section>

          <section className="panel">
            <h3 style={{ marginTop: 0 }}>Upcoming reminders</h3>
            <div className="list">
              {upcoming.map((item) => (
                <div key={item.id} className={`reminder-card ${item.type === 'fee' ? 'fee' : ''}`}>
                  <strong>{item.title}</strong>
                  <div className="muted">{item.date} • {item.venue}</div>
                  <div>{item.reminder}</div>
                  <div className="muted">Fee: {item.fee || 0}</div>
                  <div style={{ marginTop: 8 }}>
                    {activeReminderId === item.id ? (
                      <div className="field-group">
                        <label>Custom reminder message</label>
                        <textarea value={customReminderText} onChange={(e) => setCustomReminderText(e.target.value)} rows="4" style={{ width: '100%', padding: '10px 12px', borderRadius: '10px', border: '1px solid rgba(255,255,255,0.15)', background: 'var(--panel-2)', color: 'var(--text)' }} />
                        <div className="actions">
                          <button className="btn" onClick={() => setActiveReminderId(null)}>Cancel</button>
                          <button className="btn btn-primary" onClick={() => sendWhatsAppReminder(item)}>Send reminder</button>
                        </div>
                      </div>
                    ) : (
                      <button className="btn btn-primary" onClick={() => openReminderComposer(item)}>Reminder</button>
                    )}
                  </div>
                  {item.type === 'match' && (
                    <div style={{ marginTop: 8 }}>
                      {editingMatchId === item.id ? (
                        <div className="field-group">
                          <input type="date" value={editForm.date} onChange={(e) => setEditForm((prev) => ({ ...prev, date: e.target.value }))} />
                          <input value={editForm.slot} onChange={(e) => setEditForm((prev) => ({ ...prev, slot: e.target.value }))} placeholder="Slot" />
                          <div className="actions">
                            <button className="btn" onClick={() => setEditingMatchId(null)}>Cancel</button>
                            <button className="btn btn-primary" onClick={saveEdit}>Save</button>
                          </div>
                        </div>
                      ) : (
                        <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
                          <button className="btn" onClick={() => startEdit(item)}>Edit day & time</button>
                          <button className="btn" style={{ background: '#ff5f7e', color: 'white' }} onClick={() => deleteMatch(item.id)}>Delete</button>
                        </div>
                      )}
                    </div>
                  )}
                </div>
              ))}
            </div>
          </section>
        </div>
      )}

      {showModal && (
        <div className="modal-overlay" onClick={() => setShowModal(false)}>
          <div className="modal-card" onClick={(e) => e.stopPropagation()}>
            <h3 style={{ marginTop: 0 }}>Create tournament entry</h3>
            <form onSubmit={handleSubmit}>
              <div className="field-group">
                <label>Title</label>
                <input name="title" value={form.title} onChange={handleChange} placeholder="Example: Practice Match" />
              </div>
              <div className="field-row">
                <div className="field-group">
                  <label>Date</label>
                  <input type="date" name="date" value={form.date} onChange={handleChange} />
                </div>
                <div className="field-group">
                  <label>Type</label>
                  <select name="type" value={form.type} onChange={handleChange}>
                    <option value="match">Match</option>
                    <option value="fee">Fee Reminder</option>
                  </select>
                </div>
              </div>
              <div className="field-row">
                <div className="field-group">
                  <label>Venue</label>
                  <input name="venue" value={form.venue} onChange={handleChange} placeholder="Main Ground" />
                </div>
                <div className="field-group">
                  <label>Fee (₹)</label>
                  <input type="number" name="fee" value={form.fee} onChange={handleChange} placeholder="1200" />
                </div>
              </div>
              <div className="field-group">
                <label>Reminder / Note</label>
                <input name="reminder" value={form.reminder} onChange={handleChange} placeholder="Team briefing at 6 PM" />
              </div>
              <div className="field-group">
                <label>Mobile number for WhatsApp</label>
                <input name="mobile" value={form.mobile} onChange={handleChange} placeholder="91XXXXXXXXXX" />
              </div>
              {warning ? <div className="warning">{warning}</div> : null}
              <div className="actions">
                <button type="button" className="btn" onClick={() => setShowModal(false)}>Cancel</button>
                <button type="submit" className="btn btn-primary">Save Entry</button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}

ReactDOM.createRoot(document.getElementById('root')).render(<App />);
